[2022-10-08T10:49:56.289+0000] {processor.py:156} INFO - Started process (PID=8257) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:49:56.290+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:49:56.290+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:49:56.290+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:49:56.292+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:49:56.291+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 7
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:49:56.292+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:49:56.379+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.092 seconds
[2022-10-08T10:49:58.168+0000] {processor.py:156} INFO - Started process (PID=8300) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:49:58.169+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:49:58.169+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:49:58.169+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:49:58.171+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:49:58.170+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 7
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:49:58.171+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:49:58.189+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.023 seconds
[2022-10-08T10:49:59.472+0000] {processor.py:156} INFO - Started process (PID=8360) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:49:59.473+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:49:59.474+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:49:59.473+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:49:59.475+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:49:59.474+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 7
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:49:59.476+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:49:59.492+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.023 seconds
[2022-10-08T10:50:03.498+0000] {processor.py:156} INFO - Started process (PID=8367) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:03.498+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:50:03.499+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:50:03.499+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:03.500+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:50:03.500+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 7
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:50:03.501+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:03.517+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.022 seconds
[2022-10-08T10:50:15.582+0000] {processor.py:156} INFO - Started process (PID=8381) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:15.583+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:50:15.584+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:50:15.583+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:15.585+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:50:15.584+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:50:15.585+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:15.601+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.021 seconds
[2022-10-08T10:50:17.608+0000] {processor.py:156} INFO - Started process (PID=8386) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:17.608+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:50:17.609+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:50:17.609+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:17.610+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:50:17.610+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:50:17.611+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:17.626+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.021 seconds
[2022-10-08T10:50:20.212+0000] {processor.py:156} INFO - Started process (PID=8440) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:20.212+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:50:20.213+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:50:20.213+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:20.215+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:50:20.214+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:50:20.215+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:20.279+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.070 seconds
[2022-10-08T10:50:23.623+0000] {processor.py:156} INFO - Started process (PID=8450) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:23.623+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:50:23.624+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:50:23.624+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:23.625+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:50:23.625+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:50:23.626+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:23.642+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.023 seconds
[2022-10-08T10:50:54.512+0000] {processor.py:156} INFO - Started process (PID=8662) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:54.514+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:50:54.514+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:50:54.514+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:54.516+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:50:54.515+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:50:54.516+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:50:54.532+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.022 seconds
[2022-10-08T10:51:25.401+0000] {processor.py:156} INFO - Started process (PID=8865) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:51:25.402+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:51:25.403+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:51:25.403+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:51:25.405+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:51:25.404+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:51:25.405+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:51:25.421+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.022 seconds
[2022-10-08T10:51:55.518+0000] {processor.py:156} INFO - Started process (PID=9077) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:51:55.519+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:51:55.520+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:51:55.519+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:51:55.522+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:51:55.521+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:51:55.523+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:51:55.539+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.023 seconds
[2022-10-08T10:52:06.810+0000] {processor.py:156} INFO - Started process (PID=9226) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:06.811+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:06.811+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:06.811+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:06.813+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:06.812+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:06.813+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:06.830+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.023 seconds
[2022-10-08T10:52:08.825+0000] {processor.py:156} INFO - Started process (PID=9231) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:08.825+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:08.826+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:08.826+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:08.828+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:08.827+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:08.828+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:08.846+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.024 seconds
[2022-10-08T10:52:10.870+0000] {processor.py:156} INFO - Started process (PID=9236) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:10.870+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:10.871+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:10.871+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:10.872+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:10.872+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:10.873+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:10.889+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.021 seconds
[2022-10-08T10:52:12.889+0000] {processor.py:156} INFO - Started process (PID=9241) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:12.890+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:12.890+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:12.890+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:12.892+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:12.891+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:12.892+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:12.909+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.022 seconds
[2022-10-08T10:52:14.927+0000] {processor.py:156} INFO - Started process (PID=9255) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:14.928+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:14.928+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:14.928+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:14.930+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:14.929+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:14.930+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:14.945+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.020 seconds
[2022-10-08T10:52:15.944+0000] {processor.py:156} INFO - Started process (PID=9260) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:15.945+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:15.945+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:15.945+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:15.947+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:15.946+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:15.947+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:15.963+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.021 seconds
[2022-10-08T10:52:17.980+0000] {processor.py:156} INFO - Started process (PID=9265) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:17.980+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:17.981+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:17.981+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:17.982+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:17.982+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:17.983+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:17.998+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.020 seconds
[2022-10-08T10:52:23.958+0000] {processor.py:156} INFO - Started process (PID=9315) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:23.959+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:23.959+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:23.959+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:23.961+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:23.960+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:23.962+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:23.978+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.022 seconds
[2022-10-08T10:52:25.990+0000] {processor.py:156} INFO - Started process (PID=9327) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:25.990+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:25.991+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:25.991+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:25.993+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:25.992+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:25.993+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:26.074+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.088 seconds
[2022-10-08T10:52:27.083+0000] {processor.py:156} INFO - Started process (PID=9334) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:27.083+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:27.084+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:27.084+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:27.086+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:27.085+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:27.086+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:27.104+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.024 seconds
[2022-10-08T10:52:29.877+0000] {processor.py:156} INFO - Started process (PID=9372) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:29.877+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:29.878+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:29.878+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:29.880+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:29.879+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:29.880+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:29.898+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.024 seconds
[2022-10-08T10:52:31.400+0000] {processor.py:156} INFO - Started process (PID=9399) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:31.401+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:31.401+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:31.401+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:31.403+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:31.402+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:31.403+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:31.421+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.024 seconds
[2022-10-08T10:52:33.613+0000] {processor.py:156} INFO - Started process (PID=9452) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:33.614+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:33.614+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:33.614+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:33.616+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:33.615+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:33.616+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:33.675+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.065 seconds
[2022-10-08T10:52:36.222+0000] {processor.py:156} INFO - Started process (PID=9489) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:36.222+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:36.223+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:36.223+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:36.224+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:36.223+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:36.224+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:36.241+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.021 seconds
[2022-10-08T10:52:43.266+0000] {processor.py:156} INFO - Started process (PID=9503) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:43.267+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:43.267+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:43.267+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:43.271+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:43.270+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 9, in <module>
    t1 = EmptyOperator(task_id="t1")
NameError: name 'EmptyOperator' is not defined
[2022-10-08T10:52:43.271+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:43.286+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.022 seconds
[2022-10-08T10:52:45.298+0000] {processor.py:156} INFO - Started process (PID=9508) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:45.298+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:45.299+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:45.299+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:45.301+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:45.300+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 3, in <module>
    f
NameError: name 'f' is not defined
[2022-10-08T10:52:45.301+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:45.317+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.022 seconds
[2022-10-08T10:52:47.326+0000] {processor.py:156} INFO - Started process (PID=9513) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:47.326+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:47.327+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:47.327+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:47.328+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:47.327+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 3
    from
       ^
SyntaxError: invalid syntax
[2022-10-08T10:52:47.328+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:47.344+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.021 seconds
[2022-10-08T10:52:52.167+0000] {processor.py:156} INFO - Started process (PID=9567) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:52.168+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:52.168+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:52.168+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:52.170+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:52.169+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2022-10-08T10:52:52.170+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:52.187+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.024 seconds
[2022-10-08T10:52:56.229+0000] {processor.py:156} INFO - Started process (PID=9577) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:56.230+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:56.230+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:56.230+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:56.232+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:56.231+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 3
    from airflow.oper
                    ^
SyntaxError: invalid syntax
[2022-10-08T10:52:56.232+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:56.248+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.021 seconds
[2022-10-08T10:52:57.241+0000] {processor.py:156} INFO - Started process (PID=9582) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:57.242+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:52:57.242+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:57.242+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:57.244+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:52:57.243+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 3
    from airflow.opera
                     ^
SyntaxError: invalid syntax
[2022-10-08T10:52:57.244+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:52:57.261+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.023 seconds
[2022-10-08T10:53:00.491+0000] {processor.py:156} INFO - Started process (PID=9632) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:00.492+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:53:00.492+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:00.492+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:00.495+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:00.494+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 3
    from airflow.operator
                        ^
SyntaxError: invalid syntax
[2022-10-08T10:53:00.495+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:00.566+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.077 seconds
[2022-10-08T10:53:04.285+0000] {processor.py:156} INFO - Started process (PID=9699) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:04.286+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:53:04.287+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:04.286+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:04.288+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:04.287+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 3
    from airflow.operators.
                          ^
SyntaxError: invalid syntax
[2022-10-08T10:53:04.289+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:04.305+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.022 seconds
[2022-10-08T10:53:06.931+0000] {processor.py:156} INFO - Started process (PID=9741) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:06.932+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:53:06.932+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:06.932+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:06.934+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:06.933+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 3
    from airflow.operators.empty
                               ^
SyntaxError: invalid syntax
[2022-10-08T10:53:06.935+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:06.951+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.023 seconds
[2022-10-08T10:53:10.954+0000] {processor.py:156} INFO - Started process (PID=9746) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:10.955+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:53:10.956+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:10.956+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:10.958+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:10.957+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 3
    from airflow.operators.empty import
                                      ^
SyntaxError: invalid syntax
[2022-10-08T10:53:10.958+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:10.976+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.025 seconds
[2022-10-08T10:53:14.003+0000] {processor.py:156} INFO - Started process (PID=9760) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:14.003+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:53:14.004+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:14.004+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:14.007+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:14.007+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 3, in <module>
    from airflow.operators.empty import Empty
ImportError: cannot import name 'Empty' from 'airflow.operators.empty' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/empty.py)
[2022-10-08T10:53:14.008+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:14.024+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.023 seconds
[2022-10-08T10:53:19.035+0000] {processor.py:156} INFO - Started process (PID=9765) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:19.036+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:53:19.036+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:19.036+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:19.047+0000] {processor.py:768} INFO - DAG(s) dict_keys(['my_dag']) retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:19.162+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:19.162+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:my_dag
[2022-10-08T10:53:19.170+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:19.170+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:my_dag
[2022-10-08T10:53:19.175+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:19.175+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:my_dag
[2022-10-08T10:53:19.176+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:19.176+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-08T10:53:19.188+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:19.188+0000] {dag.py:2594} INFO - Creating ORM DAG for my_dag
[2022-10-08T10:53:19.198+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:19.198+0000] {dag.py:3328} INFO - Setting next_dagrun for my_dag to None, run_after=None
[2022-10-08T10:53:19.213+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.180 seconds
[2022-10-08T10:53:20.243+0000] {processor.py:156} INFO - Started process (PID=9770) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:20.244+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:53:20.245+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:20.244+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:20.257+0000] {processor.py:768} INFO - DAG(s) dict_keys(['my_dag']) retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:20.282+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:20.281+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-08T10:53:20.306+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:20.306+0000] {dag.py:3328} INFO - Setting next_dagrun for my_dag to None, run_after=None
[2022-10-08T10:53:20.324+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.084 seconds
[2022-10-08T10:53:50.979+0000] {processor.py:156} INFO - Started process (PID=9982) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:50.980+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:53:50.980+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:50.980+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:50.991+0000] {processor.py:768} INFO - DAG(s) dict_keys(['my_dag']) retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:53:51.026+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:51.026+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-08T10:53:51.049+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:53:51.049+0000] {dag.py:3328} INFO - Setting next_dagrun for my_dag to None, run_after=None
[2022-10-08T10:53:51.065+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.088 seconds
[2022-10-08T10:54:21.733+0000] {processor.py:156} INFO - Started process (PID=10194) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:54:21.734+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:54:21.735+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:54:21.734+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:54:21.763+0000] {processor.py:768} INFO - DAG(s) dict_keys(['my_dag']) retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:54:21.799+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:54:21.799+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-08T10:54:21.863+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:54:21.862+0000] {dag.py:3328} INFO - Setting next_dagrun for my_dag to None, run_after=None
[2022-10-08T10:54:21.879+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.148 seconds
[2022-10-08T10:54:52.270+0000] {processor.py:156} INFO - Started process (PID=10397) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:54:52.271+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:54:52.271+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:54:52.271+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:54:52.282+0000] {processor.py:768} INFO - DAG(s) dict_keys(['my_dag']) retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:54:52.316+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:54:52.316+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-08T10:54:52.339+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:54:52.339+0000] {dag.py:3328} INFO - Setting next_dagrun for my_dag to None, run_after=None
[2022-10-08T10:54:52.356+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.089 seconds
[2022-10-08T10:55:02.012+0000] {processor.py:156} INFO - Started process (PID=10456) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:55:02.013+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:55:02.013+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:55:02.013+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:55:02.020+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:55:02.019+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 11, in <module>
    t1 = EmptyOperator(task_id="t1")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 773, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py", line 213, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 't1' has already been added to the DAG
[2022-10-08T10:55:02.020+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:55:02.037+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.028 seconds
[2022-10-08T10:55:04.909+0000] {processor.py:156} INFO - Started process (PID=10516) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:55:04.909+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:55:04.910+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:55:04.910+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:55:04.916+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:55:04.915+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dags.py", line 11, in <module>
    t2 = EmptyOperator(task_id="t1")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 773, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py", line 213, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 't1' has already been added to the DAG
[2022-10-08T10:55:04.916+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:55:04.932+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.025 seconds
[2022-10-08T10:55:07.771+0000] {processor.py:156} INFO - Started process (PID=10590) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:55:07.772+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:55:07.772+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:55:07.772+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:55:07.784+0000] {processor.py:768} INFO - DAG(s) dict_keys(['my_dag']) retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:55:07.857+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:55:07.857+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-08T10:55:07.879+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:55:07.879+0000] {dag.py:3328} INFO - Setting next_dagrun for my_dag to None, run_after=None
[2022-10-08T10:55:07.900+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.131 seconds
[2022-10-08T10:55:38.397+0000] {processor.py:156} INFO - Started process (PID=10793) to work on /opt/airflow/dags/my_dags.py
[2022-10-08T10:55:38.398+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dags.py for tasks to queue
[2022-10-08T10:55:38.398+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:55:38.398+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dags.py
[2022-10-08T10:55:38.409+0000] {processor.py:768} INFO - DAG(s) dict_keys(['my_dag']) retrieved from /opt/airflow/dags/my_dags.py
[2022-10-08T10:55:38.454+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:55:38.454+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-10-08T10:55:38.487+0000] {logging_mixin.py:117} INFO - [2022-10-08T10:55:38.487+0000] {dag.py:3328} INFO - Setting next_dagrun for my_dag to None, run_after=None
[2022-10-08T10:55:38.504+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dags.py took 0.109 seconds
